# minitest specifics
AllCops:
  TargetRubyVersion: 2.3
Metrics/LineLength:
  Max: 119
Metrics/MethodLength:
  Exclude:
    - test/**/*
Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false
