require:
  - rubocop-defaults

# minitest specifics
Metrics/MethodLength:
  Exclude:
    - test/**/*
Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*
Style/FileName:
  Exclude:
    - lib/dry-request_handler.rb
